server:
  port: 8080

spring:
  datasource:
    username: root
    password: 7981375
    url: jdbc:mysql://localhost:3306/phonocardiogram?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.phonocardiogram.entity

#showSql
logging:
  level:
    org:
      phonocardiogram:
        dao : debug